spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kaigian-mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  redis:
    host: localhost # Redis服务器地址
    abase: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password:  # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）

jwt:
  secret: secretKey #服务端私钥（一定不能泄露）
  expiration: 86400 #过期时间 60*60*24  =一天
  tokenHead: KaiGian #jwt规范  #告诉客户端jwt令牌开头需要加的一个字符串
  tokenHeader: Authorization #告诉客户端你要在请求头里面传什么参数名字